title: NT@B Textbook
description: Official NT@B Textbook
theme: just-the-docs
# logo: 
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "vendor"]

url: https://postybaloney.github.io/ntab_edu_textbook1

aux_links:
  Template Repository: https://github.com/postybaloney/ntab_edu_textbook1

  under_construction: true
