title: NT@B Textbook
description: Official NT@B Textbook
# logo: 
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "vendor"]

url: https://postybaloney.github.io/ntab_edu_textbook1

color_scheme: dark
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Template Repository: https://github.com/postybaloney/ntab_edu_textbook1
  Dark Mode:
    - '#'
  Ed:
    - 'https://edstem.org/us/courses/53369/discussion/'
  OH Queue:
    - 'https://oh.datastructur.es/'
  Beacon:
    - 'https://beacon.datastructur.es/'

footer_content:

under_construction: true
