title: NT@B Textbook
description: Official NT@B Textbook
theme: just-the-docs
# logo: "/assets/images/oohwowlogo.png"
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "vendor"]

url: 'https://postybaloney.github.io/'
baseurl: 'ntab_edu_textbook1/' # if you're using custom domain keep this blank example: baseurl: ''

color_scheme: dark
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Dark Mode:
    - '#'
  NT@B GitHub Repo:
    - 'https://github.com/neurotech-berkeley'
  NT@B Website:
    - 'https://neurotech.berkeley.edu/index.html'

footer_content:

callouts:
  warning:
    title: Warning
    color: red

under_construction: false
